set (
	BUILD_LIST_COMMON
    ./lua-5.4.4/ lua_dir
    ./examples/customization/ customization_dir
    ./examples/require_dll_example/ require_dll_example_dir
    
	./examples/source_proj/allocation_limit/ source_allocation_limit_dir 
	./examples/source_proj/any_return/ source_any_return_dir 
	./examples/source_proj/args_from_container/ source_args_from_container_dir 
	./examples/source_proj/as_returns/ source_as_returns_dir 
	./examples/source_proj/basic/ source_basic_dir 
	./examples/source_proj/calling_lua_functions/ source_calling_lua_functions_dir 
	./examples/source_proj/config/ source_config_dir 
	./examples/source_proj/containers/ source_containers_dir 
	./examples/source_proj/containers_as_table/ source_containers_as_table_dir 
	./examples/source_proj/container_usertype_as_container/ source_container_usertype_as_container_dir 
	./examples/source_proj/container_with_pairs/ source_container_with_pairs_dir 
	./examples/source_proj/coroutine/ source_coroutine_dir 
	./examples/source_proj/coroutine_multiple_stacks/ source_coroutine_multiple_stacks_dir 
	./examples/source_proj/coroutine_state/ source_coroutine_state_dir 
	./examples/source_proj/customization_base_object_catch/ source_customization_base_object_catch_dir 
	./examples/source_proj/customization_convert_on_get/ source_customization_convert_on_get_dir 
	./examples/source_proj/customization_global_transparent_argument/ source_customization_global_transparent_argument_dir 
	./examples/source_proj/customization_multiple/ source_customization_multiple_dir 
	./examples/source_proj/custom_reader/ source_custom_reader_dir 
	./examples/source_proj/c_array/ source_c_array_dir 
	./examples/source_proj/c_call/ source_c_call_dir 
	./examples/source_proj/dump/ source_dump_dir 
	./examples/source_proj/dynamic_object/ source_dynamic_object_dir 
	./examples/source_proj/environments/ source_environments_dir 
	./examples/source_proj/environments_on_functions/ source_environments_on_functions_dir 
	./examples/source_proj/environment_snooping/ source_environment_snooping_dir 
	./examples/source_proj/environment_state/ source_environment_state_dir 
	./examples/source_proj/environment_state_2/ source_environment_state_2_dir 
	./examples/source_proj/error_handler/ source_error_handler_dir 
	./examples/source_proj/exception_handler/ source_exception_handler_dir 
	./examples/source_proj/functions/ source_functions_dir 
	./examples/source_proj/functions_empty_arguments/ source_functions_empty_arguments_dir 
	./examples/source_proj/index_and_newindex_usertype/ source_index_and_newindex_usertype_dir 
	./examples/source_proj/indirect_function_calls/ source_indirect_function_calls_dir 
	./examples/source_proj/lua_stream/ source_lua_stream_dir 
	./examples/source_proj/lua_value/ source_lua_value_dir 
	./examples/source_proj/metatable_customization/ source_metatable_customization_dir 
	./examples/source_proj/metatable_key_low_level/ source_metatable_key_low_level_dir 
	./examples/source_proj/multi_results/ source_multi_results_dir 
	./examples/source_proj/optional_with_iteration/ source_optional_with_iteration_dir 
	./examples/source_proj/overloading/ source_overloading_dir 
	./examples/source_proj/overloading_with_fallback/ source_overloading_with_fallback_dir 
	./examples/source_proj/overloading_with_members/ source_overloading_with_members_dir 
	./examples/source_proj/overridable_function_members/ source_overridable_function_members_dir 
	./examples/source_proj/pairs/ source_pairs_dir 
	./examples/source_proj/pairs_with_raw_functions/ source_pairs_with_raw_functions_dir 
	./examples/source_proj/property/ source_property_dir 
	./examples/source_proj/protect/ source_protect_dir 
	./examples/source_proj/protected_functions/ source_protected_functions_dir 
	./examples/source_proj/read_only/ source_read_only_dir 
	./examples/source_proj/require/ source_require_dir 
	./examples/source_proj/require_override_behavior/ source_require_override_behavior_dir 
	./examples/source_proj/runtime_additions/ source_runtime_additions_dir 
	./examples/source_proj/script_error_handling/ source_script_error_handling_dir 
	./examples/source_proj/self_from_lua/ source_self_from_lua_dir 
	./examples/source_proj/shared_ptr/ source_shared_ptr_dir 
	./examples/source_proj/shared_ptr_inheritance/ source_shared_ptr_inheritance_dir 
	./examples/source_proj/shared_ptr_modify_in_place/ source_shared_ptr_modify_in_place_dir 
	./examples/source_proj/singleton/ source_singleton_dir 
	./examples/source_proj/stack_aligned_function/ source_stack_aligned_function_dir 
	./examples/source_proj/stack_aligned_stack_handler_function/ source_stack_aligned_stack_handler_function_dir 
	./examples/source_proj/static_variables/ source_static_variables_dir 
	./examples/source_proj/tables/ source_tables_dir 
	./examples/source_proj/table_as_container/ source_table_as_container_dir 
	./examples/source_proj/table_create_if_nil/ source_table_create_if_nil_dir 
	./examples/source_proj/table_proxy/ source_table_proxy_dir 
	./examples/source_proj/this_state/ source_this_state_dir 
	./examples/source_proj/tie/ source_tie_dir 
	./examples/source_proj/unique_ptr/ source_unique_ptr_dir 
	./examples/source_proj/usertype/ source_usertype_dir 
	./examples/source_proj/usertype_advanced/ source_usertype_advanced_dir 
	./examples/source_proj/usertype_automatic_operators/ source_usertype_automatic_operators_dir 
	./examples/source_proj/usertype_basics/ source_usertype_basics_dir 
	./examples/source_proj/usertype_bitfields/ source_usertype_bitfields_dir 
	./examples/source_proj/usertype_call_from_c++/ source_usertype_call_from_c++_dir 
	./examples/source_proj/usertype_constructors/ source_usertype_constructors_dir 
	./examples/source_proj/usertype_dynamic_get_set/ source_usertype_dynamic_get_set_dir 
	./examples/source_proj/usertype_initializers/ source_usertype_initializers_dir 
	./examples/source_proj/usertype_special_functions/ source_usertype_special_functions_dir 
	./examples/source_proj/usertype_var/ source_usertype_var_dir 
	./examples/source_proj/variables/ source_variables_dir 
	./examples/source_proj/variadic_args/ source_variadic_args_dir 
	./examples/source_proj/variadic_args_into_lua/ source_variadic_args_into_lua_dir 
	./examples/source_proj/variadic_args_shifted/ source_variadic_args_shifted_dir 
	./examples/source_proj/variadic_args_storage/ source_variadic_args_storage_dir 
	./examples/source_proj/as_function/ source_as_function_dir 
	./examples/source_proj/as_function_usertype_member_variable/ source_as_function_usertype_member_variable_dir 
	./examples/source_proj/as_table_ipairs/ source_as_table_ipairs_dir 
	./examples/source_proj/coroutine_main/ source_coroutine_main_dir 
	./examples/source_proj/coroutine_thread/ source_coroutine_thread_dir 
	./examples/source_proj/inheritance/ source_inheritance_dir 
	./examples/source_proj/my_panic/ source_my_panic_dir 
	./examples/source_proj/preparing_environments/ source_preparing_environments_dir 
	./examples/source_proj/references_in_lambdas/ source_references_in_lambdas_dir 
	./examples/source_proj/runtime_extension/ source_runtime_extension_dir 
	./examples/source_proj/simple_functions/ source_simple_functions_dir 
	./examples/source_proj/simple_structs/ source_simple_structs_dir 
	./examples/source_proj/state_script_safe/ source_state_script_safe_dir 
	./examples/source_proj/state_transfer/ source_state_transfer_dir 
	./examples/source_proj/std_thread/ source_std_thread_dir 
	./examples/source_proj/erase_demo/ source_erase_demo_dir 
	./examples/source_proj/first_snippet/ source_first_snippet_dir 
	./examples/source_proj/lazy_demo/ source_lazy_demo_dir 
	./examples/source_proj/multiple_return/ source_multiple_return_dir 
	./examples/source_proj/object_lifetime/ source_object_lifetime_dir 
	./examples/source_proj/open_multiple_libraries/ source_open_multiple_libraries_dir 
	./examples/source_proj/pointer_lifetime/ source_pointer_lifetime_dir 
	./examples/source_proj/reading_functions/ source_reading_functions_dir 
	./examples/source_proj/variables_demo/ source_variables_demo_dir 
	./examples/source_proj/write_variables_demo/ source_write_variables_demo_dir 
	./examples/source_proj/writing_functions/ source_writing_functions_dir 
	./examples/source_proj/writing_member_functions/ source_writing_member_functions_dir 
	./examples/source_proj/writing_overloaded_template_functions/ source_writing_overloaded_template_functions_dir 
	./examples/source_proj/writing_template_functions/ source_writing_template_functions_dir 
	./examples/source_proj/arguments_to_scripts/ source_arguments_to_scripts_dir 
	./examples/source_proj/functions_all/ source_functions_all_dir 
	./examples/source_proj/functions_easy/ source_functions_easy_dir 
	./examples/source_proj/make_tables/ source_make_tables_dir 
	./examples/source_proj/multiple_returns_from_lua/ source_multiple_returns_from_lua_dir 
	./examples/source_proj/multiple_returns_to_lua/ source_multiple_returns_to_lua_dir 
	./examples/source_proj/namespacing/ source_namespacing_dir 
	./examples/source_proj/opening_a_state/ source_opening_a_state_dir 
	./examples/source_proj/opening_state_on_raw_lua/ source_opening_state_on_raw_lua_dir 
	./examples/source_proj/running_lua_code/ source_running_lua_code_dir 
	./examples/source_proj/running_lua_code_low_level/ source_running_lua_code_low_level_dir 
	./examples/source_proj/running_lua_code_safely/ source_running_lua_code_safely_dir 
	./examples/source_proj/self_call/ source_self_call_dir 
	./examples/source_proj/set_and_get_variables/ source_set_and_get_variables_dir 
	./examples/source_proj/set_and_get_variables_exists/ source_set_and_get_variables_exists_dir 
	./examples/source_proj/tables_and_nesting/ source_tables_and_nesting_dir 
	./examples/source_proj/userdata/ source_userdata_dir 
	./examples/source_proj/userdata_memory_reference/ source_userdata_memory_reference_dir 
	./examples/source_proj/usertypes/ source_usertypes_dir 
	./examples/source_proj/lua_inheritance/ source_lua_inheritance_dir 

)


set ( BUILD_LIST_COMMON
        ${BUILD_LIST_COMMON}
    )
	
set ( BUILD_LIST_WINDOWS
	${BUILD_LIST_COMMON}
)